=== bozhink/Code-Chunks/workspace/Pensoft/Altova/MapForce2013/MapForceExamples/BranchOffices.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 4 U (http://www.xmlspy.com) by Mr. Nobody (Altova) -->
<xs:schema elementFormDefault="qualified" attributeFormDefault="unqualified" xmlns:sql="urn:schemas-microsoft-com:mapping-schema" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="BranchOffices" sql:relation="Altova">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Name" nillable="true" sql:relation="Altova" sql:field="Name" sql:datatype="nvarchar">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="255"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element ref="Office" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="Altova_UniqueKey">
			<xs:selector xpath="."/>
			<xs:field xpath="PrimaryKey"/>
		</xs:unique>
	</xs:element>
	<xs:element name="Office" sql:relation="Office">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Name" nillable="true" sql:relation="Office" sql:field="Name" sql:datatype="nvarchar">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="255"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="EMail" nillable="true" sql:relation="Office" sql:field="EMail" sql:datatype="nvarchar">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="255"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Fax" nillable="true" sql:relation="Office" sql:field="Fax" sql:datatype="nvarchar">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="255"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Phone" nillable="true" sql:relation="Office" sql:field="Phone" sql:datatype="nvarchar">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="255"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Location" type="xs:string" minOccurs="0"/>
				<xs:element ref="Address" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="Contact" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="Office_UniqueKey">
			<xs:selector xpath="."/>
			<xs:field xpath="PrimaryKey"/>
		</xs:unique>
		<xs:keyref name="Office_To_Altova" refer="Altova_UniqueKey">
			<xs:selector xpath="."/>
			<xs:field xpath="ForeignKey"/>
		</xs:keyref>
	</xs:element>
	<xs:element name="Address" sql:relation="Address">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="city" nillable="true" sql:relation="Address" sql:field="city" sql:datatype="nvarchar">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="255"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="state" nillable="true" sql:relation="Address" sql:field="state" sql:datatype="nvarchar">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="255"/>
							<xs:enumeration value="AK"/>
							<xs:enumeration value="AL"/>
							<xs:enumeration value="AR"/>
							<xs:enumeration value="AZ"/>
							<xs:enumeration value="CA"/>
							<xs:enumeration value="CO"/>
							<xs:enumeration value="CT"/>
							<xs:enumeration value="DC"/>
							<xs:enumeration value="DE"/>
							<xs:enumeration value="FL"/>
							<xs:enumeration value="GA"/>
							<xs:enumeration value="GU"/>
							<xs:enumeration value="HI"/>
							<xs:enumeration value="IA"/>
							<xs:enumeration value="ID"/>
							<xs:enumeration value="IL"/>
							<xs:enumeration value="IN"/>
							<xs:enumeration value="KS"/>
							<xs:enumeration value="KY"/>
							<xs:enumeration value="LA"/>
							<xs:enumeration value="MA"/>
							<xs:enumeration value="MD"/>
							<xs:enumeration value="ME"/>
							<xs:enumeration value="MI"/>
							<xs:enumeration value="MN"/>
							<xs:enumeration value="MO"/>
							<xs:enumeration value="MS"/>
							<xs:enumeration value="MT"/>
							<xs:enumeration value="NC"/>
							<xs:enumeration value="ND"/>
							<xs:enumeration value="NE"/>
							<xs:enumeration value="NH"/>
							<xs:enumeration value="NJ"/>
							<xs:enumeration value="NM"/>
							<xs:enumeration value="NV"/>
							<xs:enumeration value="NY"/>
							<xs:enumeration value="OH"/>
							<xs:enumeration value="OK"/>
							<xs:enumeration value="OR"/>
							<xs:enumeration value="PA"/>
							<xs:enumeration value="PR"/>
							<xs:enumeration value="RI"/>
							<xs:enumeration value="SC"/>
							<xs:enumeration value="SD"/>
							<xs:enumeration value="TN"/>
							<xs:enumeration value="TX"/>
							<xs:enumeration value="UT"/>
							<xs:enumeration value="VA"/>
							<xs:enumeration value="VI"/>
							<xs:enumeration value="VT"/>
							<xs:enumeration value="WA"/>
							<xs:enumeration value="WI"/>
							<xs:enumeration value="WV"/>
							<xs:enumeration value="WY"/>
							<xs:enumeration value="A"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="street" nillable="true" sql:relation="Address" sql:field="street" sql:datatype="nvarchar">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="255"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="zip" nillable="true" sql:relation="Address" sql:field="zip" sql:datatype="int">
					<xs:simpleType>
						<xs:restriction base="xs:integer">
							<xs:maxInclusive value="2147483647"/>
							<xs:minInclusive value="-2147483648"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="Address_UniqueKey">
			<xs:selector xpath="."/>
			<xs:field xpath="PrimaryKey"/>
		</xs:unique>
		<xs:keyref name="Address_To_Office" refer="Office_UniqueKey">
			<xs:selector xpath="."/>
			<xs:field xpath="ForeignKey"/>
		</xs:keyref>
	</xs:element>
	<xs:element name="Contact">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="first" type="xs:string"/>
				<xs:element name="last" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== bozhink/Code-Chunks/workspace/Pensoft/Altova/MapForce2013/MapForceExamples/BranchOffice2.xml
<?xml version="1.0" encoding="UTF-8"?>
<BranchOffices xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="BranchOffices.xsd">
	<Name>Nanonull</Name>
	<Office>
		<Name>Nanonull Research Outpost</Name>
		<EMail>sp@nanonull.com</EMail>
		<Fax xsi:nil="true"/>
		<Phone>+8817 3141 5926</Phone>
		<Address>
			<city>South Pole</city>
			<state xsi:nil="true"/>
			<street xsi:nil="true"/>
			<zip xsi:nil="true"/>
		</Address>
		<Contact>
			<first>Scott</first>
			<last>Amundsen</last>
		</Contact>
	</Office>
</BranchOffices>

=== bozhink/Code-Chunks/workspace/Pensoft/Altova/MapForce2013/MapForceExamples/BranchOffices.xml
<?xml version="1.0" encoding="UTF-8"?>
<BranchOffices xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="BranchOffices.xsd">
	<Name>Nanonull</Name>
	<Office>
		<Name>Nanonull, Inc.</Name>
		<EMail>office@nanonull.com</EMail>
		<Fax>+1 (321) 555 5155 - 9</Fax>
		<Phone>+1 (321) 555 5155</Phone>
		<Address>
			<city>Vereno</city>
			<state>CA</state>
			<street>119 Oakstreet, Suite 4876</street>
			<zip>29213</zip>
		</Address>
		<Contact>
			<first>Vernon</first>
			<last>Callaby</last>
		</Contact>
		<Contact>
			<first>Frank</first>
			<last>Further</last>
		</Contact>
		<Contact>
			<first>Loby</first>
			<last>Matise</last>
		</Contact>
		<Contact>
			<first>Joe</first>
			<last>Firstbread</last>
		</Contact>
		<Contact>
			<first>Susi</first>
			<last>Sanna</last>
		</Contact>
		<Contact>
			<first>Fred</first>
			<last>Landis</last>
		</Contact>
		<Contact>
			<first>Michelle</first>
			<last>Butler</last>
		</Contact>
		<Contact>
			<first>Ted</first>
			<last>Little</last>
		</Contact>
		<Contact>
			<first>Ann</first>
			<last>Way</last>
		</Contact>
		<Contact>
			<first>Liz</first>
			<last>Gardner</last>
		</Contact>
		<Contact>
			<first>Paul</first>
			<last>Smith</last>
		</Contact>
		<Contact>
			<first>Alex</first>
			<last>Martin</last>
		</Contact>
		<Contact>
			<first>George</first>
			<last>Hammer</last>
		</Contact>
		<Contact>
			<first>Jessica</first>
			<last>Bander</last>
		</Contact>
		<Contact>
			<first>Lui</first>
			<last>King</last>
		</Contact>
	</Office>
	<Office>
		<Name>Nanonull Partners, Inc.</Name>
		<EMail>nextoffice@nanonull.com</EMail>
		<Fax>+1 (927) 555 1845</Fax>
		<Phone>+1 (927) 555 0094</Phone>
		<Address>
			<city>Brenton</city>
			<state>MA</state>
			<street>9865 Millenium Center, Suite 456</street>
			<zip>5985</zip>
		</Address>
		<Contact>
			<first>Steve</first>
			<last>Meier</last>
		</Contact>
		<Contact>
			<first>Theo</first>
			<last>Bone</last>
		</Contact>
		<Contact>
			<first>Max</first>
			<last>Nafta</last>
		</Contact>
		<Contact>
			<first>Valentin</first>
			<last>Bass</last>
		</Contact>
		<Contact>
			<first>Carl</first>
			<last>Franken</last>
		</Contact>
		<Contact>
			<first>Mark</first>
			<last>Redgreen</last>
		</Contact>
	</Office>
	<Office>
		<Name>Nanonull Holding, Inc.</Name>
		<EMail>holding@nanonull.com</EMail>
		<Fax>+1 (123) 555 2222 - 15</Fax>
		<Phone>+1 (123) 555 2222 - 0</Phone>
	</Office>
</BranchOffices>
