=== bozhink/Code-Chunks/workspace/Pensoft/Altova/MapForce2013/MapForceExamples/Employees.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by Bernhard Wallisch (Altova GmbH) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Company">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Name" type="xs:string"/>
				<xs:element name="Employees">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Manager" type="EmployeeType"/>
							<xs:element name="Programmer" type="EmployeeType"/>
							<xs:element name="Support" type="EmployeeType" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="EmployeeType">
		<xs:sequence>
			<xs:element name="FirstName" type="xs:string"/>
			<xs:element name="LastName" type="xs:string"/>
			<xs:element name="PhoneExt" type="xs:string"/>
			<xs:element name="Email" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== bozhink/Code-Chunks/workspace/Pensoft/Altova/MapForce2013/MapForceExamples/Employees.xml
<?xml version="1.0" encoding="UTF-8"?>
<Company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Employees.xsd">
	<Name>Nanonull, Inc.</Name>
	<Employees>
		<Manager>
			<FirstName>Vernon</FirstName>
			<LastName>Callaby</LastName>
			<PhoneExt>582</PhoneExt>
			<Email>v.callaby@nanonull.com</Email>
		</Manager>
		<Programmer>
			<FirstName>Frank</FirstName>
			<LastName>Further</LastName>
			<PhoneExt>471</PhoneExt>
			<Email>f.further@nanonull.com</Email>
		</Programmer>
		<Support>
			<FirstName>Loby</FirstName>
			<LastName>Matise</LastName>
			<PhoneExt>963</PhoneExt>
			<Email>l.matise@nanonull.com</Email>
		</Support>
		<Support>
			<FirstName>Susi</FirstName>
			<LastName>Sanna</LastName>
			<PhoneExt>753</PhoneExt>
			<Email>s.sanna@nanonull.com</Email>
		</Support>
	</Employees>
</Company>
