=== bozhink/Code-Chunks/workspace/Pensoft/Altova/MapForce2013/MapForceExamples/KeyValueList.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2011 rel. 2 sp1 (http://www.altova.com) by Mr. Nobody (Altova GmbH) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="KeyValueList">
		<xs:annotation>
			<xs:documentation>A generic data structure</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="1">
				<xs:element name="Item" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Property" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="Key" type="xs:string" use="required"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== bozhink/Code-Chunks/workspace/Pensoft/Altova/MapForce2013/MapForceExamples/KeyValueList.xml
<?xml version="1.0" encoding="UTF-8"?>
<KeyValueList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="KeyValueList.xsd">
	<Item>
		<Property Key="role">Manager</Property>
		<Property Key="First">Vernon</Property>
		<Property Key="Last">Callaby</Property>
	</Item>
	<Item>
		<Property Key="role">Programmer</Property>
		<Property Key="First">Frank</Property>
		<Property Key="Last">Further</Property>
	</Item>
	<Item>
		<Property Key="role">Support</Property>
		<Property Key="First">Loby</Property>
		<Property Key="Last">Matise</Property>
	</Item>
	<Item>
		<Property Key="role">Support</Property>
		<Property Key="First">Susi</Property>
		<Property Key="Last">Sanna</Property>
	</Item>
</KeyValueList>
