=== bozhink/Code-Chunks/workspace/Pensoft/Altova/MapForce2013/MapForceExamples/sales-report.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 sp1 (http://www.altova.com) by Mr. Nobody (Altova GmbH) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="sales-report">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="period" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="region-sales" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="regioncode" use="required"/>
									<xs:attribute name="amount" type="xs:decimal" use="required"/>
									<xs:attribute name="units-sold" type="xs:integer"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="start-date" type="xs:date" use="required"/>
						<xs:attribute name="end-date" type="xs:date" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== bozhink/Code-Chunks/workspace/Pensoft/Altova/MapForce2013/MapForceExamples/sales-report.xml
<?xml version="1.0" encoding="UTF-8"?>
<sales-report xsi:noNamespaceSchemaLocation="sales-report.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<period start-date="2008-01-01" end-date="2008-01-31">
		<region-sales regioncode="CA" amount="110.4"/>
		<region-sales regioncode="MA" amount="75.3"/>
	</period>
	<period start-date="2008-02-01" end-date="2008-02-29">
		<region-sales regioncode="CA" amount="114.3"/>
		<region-sales regioncode="MA" amount="65.2"/>
	</period>
	<period start-date="2008-03-01" end-date="2008-03-31">
		<region-sales regioncode="CA" amount="134.2"/>
		<region-sales regioncode="MA" amount="86.1"/>
	</period>
	<period start-date="2008-04-01" end-date="2008-04-30">
		<region-sales regioncode="CA" amount="107.3"/>
		<region-sales regioncode="MA" amount="112.1"/>
	</period>
	<period start-date="2008-05-01" end-date="2008-05-31">
		<region-sales regioncode="CA" amount="114.4"/>
		<region-sales regioncode="MA" amount="93.8"/>
	</period>
	<period start-date="2008-06-01" end-date="2008-06-30">
		<region-sales regioncode="CA" amount="113.9"/>
		<region-sales regioncode="MA" amount="72.4"/>
	</period>
	<period start-date="2008-07-01" end-date="2008-07-31">
		<region-sales regioncode="CA" amount="89.4"/>
		<region-sales regioncode="MA" amount="67.4"/>
	</period>
	<period start-date="2008-08-01" end-date="2008-08-31">
		<region-sales regioncode="CA" amount="95.3"/>
		<region-sales regioncode="MA" amount="84.9"/>
	</period>
	<period start-date="2008-09-01" end-date="2008-09-30">
		<region-sales regioncode="CA" amount="107.2"/>
		<region-sales regioncode="MA" amount="99.5"/>
	</period>
	<period start-date="2008-10-01" end-date="2008-10-31">
		<region-sales regioncode="CA" amount="129.7"/>
		<region-sales regioncode="MA" amount="82.5"/>
	</period>
	<period start-date="2008-11-01" end-date="2008-11-30">
		<region-sales regioncode="CA" amount="137.1"/>
		<region-sales regioncode="MA" amount="101.9"/>
	</period>
	<period start-date="2008-12-01" end-date="2008-12-31">
		<region-sales regioncode="CA" amount="152.6"/>
		<region-sales regioncode="MA" amount="120.6"/>
	</period>
</sales-report>
