=== bozhink/Code-Chunks/workspace/Pensoft/Altova/MapForce2013/MapForceExamples/schema-type-list.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="schema-types">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="type" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:attribute name="name" type="xs:token"/>
            <xs:attribute name="base" type="xs:token" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>      
    </xs:complexType>
    <xs:key name="type-name">
      <xs:selector xpath="type"/>
      <xs:field xpath="@name"/>
    </xs:key>
    <xs:keyref name="type-base" refer="type-name">
      <xs:selector xpath="type"/>
      <xs:field xpath="@base"/>
    </xs:keyref>
  </xs:element>
</xs:schema>

=== bozhink/Code-Chunks/workspace/Pensoft/Altova/MapForce2013/MapForceExamples/schema-type-list.xml
<?xml version="1.0" encoding="utf-8"?>
<schema-types xsi:noNamespaceSchemaLocation="schema-type-list.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <type name="xs:anyType"/>
  <type name="xs:anySimpleType" base="xs:anyType"/>
  <type name="xs:anyAtomicType" base="xs:anySimpleType"/>
  <type name="xs:string" base="xs:anyAtomicType"/>
  <type name="xs:decimal" base="xs:anyAtomicType"/>
  <type name="xs:integer" base="xs:decimal"/>
  <type name="xs:boolean" base="xs:anyAtomicType"/>
  <type name="xs:double" base="xs:anyAtomicType"/>
  <type name="xs:float" base="xs:anyAtomicType"/>
  <type name="xs:duration" base="xs:anyAtomicType"/>
  <type name="xs:dayTimeDuration" base="xs:duration"/>
  <type name="xs:yearMonthDuration" base="xs:duration"/>
  <type name="xs:dateTime" base="xs:anyAtomicType"/>
  <type name="xs:date" base="xs:anyAtomicType"/>
  <type name="xs:time" base="xs:anyAtomicType"/>
  <type name="xs:gYearMonth" base="xs:anyAtomicType"/>
  <type name="xs:gMonthDay" base="xs:anyAtomicType"/>
  <type name="xs:gYear" base="xs:anyAtomicType"/>
  <type name="xs:gMonth" base="xs:anyAtomicType"/>
  <type name="xs:gDay" base="xs:anyAtomicType"/>
  <type name="xs:base64Binary" base="xs:anyAtomicType"/>
  <type name="xs:hexBinary" base="xs:anyAtomicType"/>
  <type name="xs:anyURI" base="xs:anyAtomicType"/>
  <type name="xs:QName" base="xs:anyAtomicType"/>
  <type name="xs:untypedAtomic" base="xs:anyAtomicType"/>
  <type name="xs:NOTATION" base="xs:anyAtomicType"/>
  <type name="xs:IDREFS" base="xs:IDREF"/>
  <type name="xs:NMTOKENS" base="xs:NMTOKEN"/>
  <type name="xs:ENTITIES" base="xs:ENTITIES"/>
  <type name="xs:normalizedString" base="xs:string"/>
  <type name="xs:token" base="xs:normalizedString"/>
  <type name="xs:language" base="xs:token"/>
  <type name="xs:NMTOKEN" base="xs:token"/>
  <type name="xs:Name" base="xs:token"/>
  <type name="xs:NCName" base="xs:Name"/>
  <type name="xs:ID" base="xs:NCName"/>
  <type name="xs:IDREF" base="xs:NCName"/>
  <type name="xs:ENTITY" base="xs:NCName"/>
  <type name="xs:nonPositiveInteger" base="xs:integer"/>
  <type name="xs:negativeInteger" base="xs:nonPositiveInteger"/>
  <type name="xs:long" base="xs:integer"/>
  <type name="xs:int" base="xs:long"/>
  <type name="xs:short" base="xs:int"/>
  <type name="xs:byte" base="xs:short"/>
  <type name="xs:nonNegativeInteger" base="xs:integer"/>
  <type name="xs:positiveInteger" base="xs:nonNegativeInteger"/>
  <type name="xs:unsignedLong" base="xs:nonNegativeInteger"/>
  <type name="xs:unsignedInt" base="xs:unsignedLong"/>
  <type name="xs:unsignedShort" base="xs:unsignedInt"/>
  <type name="xs:unsignedByte" base="xs:unsignedShort"/>
</schema-types>
