=== bozhink/Code-Chunks/workspace/Pensoft/Altova/MapForce2013/MapForceExamples/Temperatures.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2011 (x64) (http://www.altova.com) by Mr. Nobody (Altova GmbH) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="data">
		<xs:complexType>
			<xs:attribute name="temp" type="xs:decimal" use="required"/>
			<xs:attribute name="month" type="xs:gYearMonth" use="required"/>
			<xs:attribute name="desc"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Temperatures">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="data" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== bozhink/Code-Chunks/workspace/Pensoft/Altova/MapForce2013/MapForceExamples/Temperatures.xml
<?xml version="1.0" encoding="UTF-8"?>
<Temperatures xsi:noNamespaceSchemaLocation="Temperatures.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<data temp="-3.6" month="2006-01" />
	<data temp="-0.7" month="2006-02" />
	<data temp="7.5" month="2006-03" />
	<data temp="12.4" month="2006-04" />
	<data temp="16.2" month="2006-05" />
	<data temp="19" month="2006-06" />
	<data temp="22.7" month="2006-07" />
	<data temp="23.2" month="2006-08" />
	<data temp="18.7" month="2006-09" />
	<data temp="11.2" month="2006-10" />
	<data temp="9.1" month="2006-11" />
	<data temp="0.8" month="2006-12" />
	<data temp="-3.2" month="2007-01" />
	<data temp="-0.3" month="2007-02" />
	<data temp="6.5" month="2007-03" />
	<data temp="10.6" month="2007-04" />
	<data temp="19" month="2007-05" />
	<data temp="20.3" month="2007-06" />
	<data temp="22.3" month="2007-07" />
	<data temp="20.7" month="2007-08" />
	<data temp="19.2" month="2007-09" />
	<data temp="12.9" month="2007-10" />
	<data temp="8.1" month="2007-11" />
	<data temp="1.9" month="2007-12" />
	<data temp="1.7" month="2008-01" />
	<data temp="1.6" month="2008-02" />
	<data temp="2.5" month="2008-03" />
	<data temp="11.6" month="2008-04" />
	<data temp="13.2" month="2008-05" />
	<data temp="21.5" month="2008-06" />
	<data temp="24" month="2008-07" />
	<data temp="23.8" month="2008-08" />
	<data temp="20" month="2008-09" />
	<data temp="12.7" month="2008-10" />
	<data temp="7.1" month="2008-11" />
	<data temp="-0.5" month="2008-12" />
	<data temp="-1.6" month="2009-01" />
	<data temp="1.2" month="2009-02" />
	<data temp="5.8" month="2009-03" />
	<data temp="14.3" month="2009-04" />
	<data temp="16.3" month="2009-05" />
	<data temp="18.2" month="2009-06" />
	<data temp="21.4" month="2009-07" />
	<data temp="21.1" month="2009-08" />
	<data temp="17.2" month="2009-09" />
	<data temp="9.9" month="2009-10" />
	<data temp="6.8" month="2009-11" />
	<data temp="1.4" month="2009-12" />
	<data temp="-1.9" month="2010-01" />
	<data temp="0.9" month="2010-02" />
	<data temp="6.3" month="2010-03" />
	<data temp="10.8" month="2010-04" />
	<data temp="14.7" month="2010-05" />
	<data temp="19.2" month="2010-06" />
	<data temp="22.3" month="2010-07" />
	<data temp="19.5" month="2010-08" />
	<data temp="14.2" month="2010-09" />
	<data temp="7.8" month="2010-10" />
	<data temp="6.9" month="2010-11" />
	<data temp="-1.0" month="2010-12" />
</Temperatures>
