=== bozhink/Code-Chunks/workspace/Pensoft/Altova/MapForce2013/MapForceExamples/Tutorial/input.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- edited with XMLSpy v2005 rel. 3 U (http://www.altova.com) by Mr. Nobody (Altova GmbH) -->
<!--W3C Schema generated by XMLSpy v2005 rel. 3 U (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="Input">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Products" type="ProductGroup"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Amount" type="xs:integer"/>
	<xs:element name="Name">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Price" type="xs:integer"/>
	<xs:complexType name="ProductType">
		<xs:sequence>
			<xs:element ref="Name"/>
			<xs:element ref="Amount"/>
			<xs:element ref="Price"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ProductGroup">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="Product" type="ProductType"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== bozhink/Code-Chunks/workspace/Pensoft/Altova/MapForce2013/MapForceExamples/Tutorial/input.xml
<?xml version="1.0" encoding="UTF-8"?>
<Input xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="input.xsd">
	<Products>
		<Product>
			<Name>ProductA</Name>
			<Amount>10</Amount>
			<Price>5</Price>
		</Product>
		<Product>
			<Name>ProductB</Name>
			<Amount>5</Amount>
			<Price>20</Price>
		</Product>
	</Products>
</Input>
