=== bozhink/Code-Chunks/workspace/Pensoft/Altova/MapForce2013/MapForceExamples/Tutorial/Tut-company.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--W3C Schema generated by XMLSpy v2005 sp1 U (http://www.xmlspy.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Altova">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Name" type="xs:string"/>
				<xs:element name="Office" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Name" type="xs:string"/>
							<xs:element name="street" type="xs:string"/>
							<xs:element name="city" type="xs:string"/>
							<xs:element name="Phone" type="xs:integer"/>
							<xs:element name="Department" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Name" type="xs:string"/>
										<xs:element name="Person" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="EMail" type="xs:string"/>
													<xs:element name="First" type="xs:string"/>
													<xs:element name="Last" type="xs:string"/>
													<xs:element name="PhoneExt" type="xs:string"/>
													<xs:element name="Title" type="xs:string"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== bozhink/Code-Chunks/workspace/Pensoft/Altova/MapForce2013/MapForceExamples/Tutorial/Tut-company.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2005 sp1 U (http://www.xmlspy.com) by Mr. Nobody (Altova GmbH) -->
<!-- edited with XMLSPY v2004 rel. 4 U (http://www.xmlspy.com) by Alex (Altova GmbH) -->
<Altova xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Tut-company.xsd">
	<Name>Microtech OrgChart</Name>
	<Office>
		<Name>Microtech, Inc.</Name>
		<street>Major Ave 1</street>
		<city>Vancouver</city>
		<Phone>5588339</Phone>
		<Department>
			<Name>Admin</Name>
			<Person>
				<EMail>A.Aldrich@microtech.com</EMail>
				<First>Albert</First>
				<Last>Aldrich</Last>
				<PhoneExt>582</PhoneExt>
				<Title>Manager</Title>
			</Person>
			<Person>
				<EMail>b.bander@microtech.com</EMail>
				<First>Bert</First>
				<Last>Bander</Last>
				<PhoneExt>471</PhoneExt>
				<Title>Accounts Receivable</Title>
			</Person>
			<Person>
				<EMail>c.clovis@microtech.com</EMail>
				<First>Clive</First>
				<Last>Clovis</Last>
				<PhoneExt>963</PhoneExt>
				<Title>Accounting Manager</Title>
			</Person>
		</Department>
		<Department>
			<Name>Sales and Marketing</Name>
			<Person>
				<EMail>d.Durnell@microtech.com</EMail>
				<First>Dave</First>
				<Last>Durnelll</Last>
				<PhoneExt>621</PhoneExt>
				<Title>Marketing Manager Europe</Title>
			</Person>
			<Person>
				<EMail>e.ellas@microtech.com</EMail>
				<First>Eve</First>
				<Last>Ellas</Last>
				<PhoneExt>753</PhoneExt>
				<Title>Art Director</Title>
			</Person>
		</Department>
		<Department>
			<Name>Manufacturing</Name>
			<Person>
				<EMail>f.fortunas@microtech.com</EMail>
				<First>Fred</First>
				<Last>Fortunas</Last>
				<PhoneExt>951</PhoneExt>
				<Title>Program Manager</Title>
			</Person>
			<Person>
				<EMail>g.gundall@microtech.com</EMail>
				<First>Gerry</First>
				<Last>Gundall</Last>
				<PhoneExt>654</PhoneExt>
				<Title>Software Engineer</Title>
			</Person>
			<Person>
				<EMail>h.hardy@microtech.com</EMail>
				<First>Harry</First>
				<Last>Hardy</Last>
				<PhoneExt>852</PhoneExt>
				<Title>Software Engineer</Title>
			</Person>
			<Person>
				<EMail>i.idilko@microtech.com</EMail>
				<First>Ingrid</First>
				<Last>Idilko</Last>
				<PhoneExt>951</PhoneExt>
				<Title>Technical Writer</Title>
			</Person>
			<Person>
				<EMail>j.judy@microtech.com</EMail>
				<First>June</First>
				<Last>Judy</Last>
				<PhoneExt>753</PhoneExt>
				<Title>Software Engineer</Title>
			</Person>
			<Person>
				<EMail>k.krove@microtech.com</EMail>
				<First>Karl</First>
				<Last>Krove</Last>
				<PhoneExt>334</PhoneExt>
				<Title>Software Engineer</Title>
			</Person>
		</Department>
		<Department>
			<Name>Level 1 support</Name>
			<Person>
				<EMail>l.libby@microtech.com</EMail>
				<First>Lawrence</First>
				<Last>Libby</Last>
				<PhoneExt>778</PhoneExt>
				<Title>IT Manager</Title>
			</Person>
			<Person>
				<EMail>m.morehouse@microtech.com</EMail>
				<First>Monica</First>
				<Last>Morehouse</Last>
				<PhoneExt>223</PhoneExt>
				<Title>Web Developer</Title>
			</Person>
			<Person>
				<EMail>n.newbury@microtech.com</EMail>
				<First>Nira</First>
				<Last>Newbury</Last>
				<PhoneExt>241</PhoneExt>
				<Title>Support Engineer</Title>
			</Person>
			<Person>
				<EMail>o.origone@microtech.com</EMail>
				<First>Olanda</First>
				<Last>Origone</Last>
				<PhoneExt>345</PhoneExt>
				<Title>Support Engineer</Title>
			</Person>
		</Department>
	</Office>
	<Office>
		<Name>Microtech Partners, Inc.</Name>
		<street>Perro Bvd 1324</street>
		<city>Ottowa</city>
		<Phone>3549202</Phone>
		<Department>
			<Name>Admin</Name>
			<Person>
				<EMail>s.ponetti@microtech.com</EMail>
				<First>Paul</First>
				<Last>Ponetti</Last>
				<PhoneExt>114</PhoneExt>
				<Title>Office Manager</Title>
			</Person>
			<Person>
				<EMail>q.Quang@microtech.com</EMail>
				<First>Quang</First>
				<Last>Qui</Last>
				<PhoneExt>331</PhoneExt>
				<Title>Accounts Receivable</Title>
			</Person>
		</Department>
		<Department>
			<Name>Sales and Marketing</Name>
			<Person>
				<EMail>r.rotter@microtech.com</EMail>
				<First>Rita</First>
				<Last>Rotter</Last>
				<PhoneExt>122</PhoneExt>
				<Title>PR &amp; Marketing Manager US</Title>
			</Person>
		</Department>
		<Department>
			<Name>Level 2 support</Name>
			<Person>
				<EMail>s.semua@microtech.com</EMail>
				<First>Silla</First>
				<Last>Semua</Last>
				<PhoneExt>716</PhoneExt>
				<Title>IT Manager</Title>
			</Person>
			<Person>
				<EMail>t.tinker@microtech.com</EMail>
				<First>Tom</First>
				<Last>Tinker</Last>
				<PhoneExt>147</PhoneExt>
				<Title>Support Engineer</Title>
			</Person>
			<Person>
				<EMail>u.ugoner@microtech.com</EMail>
				<First>Uri</First>
				<Last>Ugoner</Last>
				<PhoneExt>152</PhoneExt>
				<Title>Support Engineer</Title>
			</Person>
		</Department>
	</Office>
</Altova>
